cache:
    type: internal
    host: ""
    index_name: ""
    username: ""
    password: ""
database:
    type: internal
    host: ""
    name: ""
    username: ""
    password: ""
gocqhttp:
    enable: true
    http_host: http://10.0.0.2:5700
    ws_listen: false
queue:
    type: internal
    host: ""
    index_name: ""
    username: ""
    password: ""
search:
    type: internal
    host: ""
    index_name: ""
    username: ""
    password: ""
server:
    http_port: "3000"
    ws_port: "4000"
    enable_ws: false
    debug_mode: false
    file_logger: false
