cache:
    type: internal
    host: ""
    index_name: ""
    username: ""
    password: ""
database:
    type: internal
    host: ""
    name: ""
    username: ""
    password: ""
gocqhttp:
    enable: true
    host_url: ws://10.0.0.2:28781
    delay: 3000
    enable_ws: true
mirai:
    enable: false
queue:
    type: internal
    host: ""
    index_name: ""
    username: ""
    password: ""
search:
    type: internal
    host: ""
    index_name: ""
    username: ""
    password: ""
server:
    listen_port: "3000"
    debug_mode: false
    file_logger: false
