name: NodeJS Deploy

on:
  push:
    branches:
      - "main"
      
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      -
        name: ZeroTier
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      -
        name: ping host
        shell: bash
        run: |
          count=5
          while ! ping -c 1 ${{ secrets.ZEROTIER_HOST_IP }} ; do
            echo "waiting..." ;
            sleep 1 ;
            let count=count-1
          done
          echo "ping success"
      -
        name: deploy to docker
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.ZEROTIER_HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /Users/server/Documents/NyaBot
            /usr/bin/git fetch
            /usr/bin/git pull
            /usr/local/bin/docker stop nyabot
            /usr/local/bin/docker rm nyabot
            /usr/local/bin/docker image rm whydesd/nyabot:latest
            /usr/local/bin/docker pull whydesd/nyabot:latest
            /usr/local/bin/docker create -v /Users/server/Documents/NyaBot/config.yaml:/app/config.yaml -v /Users/server/Documents/NyaBot/scripts:/app/scripts --name nyabot whydesd/nyabot:dev
            /usr/local/bin/docker start nyabot
